env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true,
    experimentalDecorators: true,
    jsx: true,
    classes: true,
  sourceType: module
plugins:
  - react
  - import
rules:
  no-console:
    - 0
  indent:
    - error
    - 4
  react/jsx-uses-vars:
    - 2
  linebreak-style:
    - error
    - windows
  semi:
    - error
    - never
  no-alert: 
    - 0
